# Generated by Django 4.2.11 on 2024-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjet',
            new_name='sujet',
        ),
    ]
